### ISSUE TITLE
Mandarin crashes

### ISSUE THREAD

**Issue by atro-city** [praydog/SH2R-UEVR#7]
I installed the latest update, and there's still a crash a few seconds into the mandarin fight in the lakeview hotel. Can't confirm the initial bug is gone, got past them on flatscreen before the fix.

**Comment by praydog** [comment]
Are you able to upload your save for me? They went away for me in the labyrinth area where they're under the floor. I just don't have a save reasonably close to the fight

**Comment by atro-city** [comment]
https://drive.google.com/file/d/1REOY0JJuKhnRB6hyWHiJIPyVmOvW1qdd/view?usp=drive_link

I already got past it flatscreen, but there should be earlier saves before that

**Comment by atro-city** [comment]
There's also a crash in the employee elevator later
